{
 "title": "Amazon EC2",
 "description": "Visualize Amazon EC2 metrics with CloudWatch",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "EC2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "namespace": "AWS/EC2",
     "metricName": "CPUUtilization",
     "region": "$region",
     "statistics": [ "Average" ],
     "period": "$period"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "namespace": "AWS/EC2",
     "metricName": "MemoryUtilization",
     "region": "$region",
     "statistics": [ "Average" ],
     "period": "$period"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "namespace": "AWS/EC2",
     "metricName": "NetworkIn",
     "region": "$region",
     "statistics": [ "Average" ],
     "period": "$period"
    },
    {
     "dimensions": { "InstanceId": "*" },
     "namespace": "AWS/EC2",
     "metricName": "NetworkOut",
     "region": "$region",
     "statistics": [ "Average" ],
     "period": "$period"
    }
   ]
  },
  {
   "title": "CPU utilization per instance [max %]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  }
 ]
}